### PR TITLE
Create Unit Test And Setup Github Action's

### PR DESCRIPTION
**Pull request by mhdiiilham**

### CODE REVIEW

**Comment by adibaulia** [comment]
bro, itu yang ```LowerCase()``` sama ```UpperCase()``` harus dichaining sama method ```Long()``` atau method ```Short()``` biar ga return string kosong. Misal:
```
fmt.Println(tanggal.NewBulan(time.Now()).Long().UpperCase()) //print OKTOBER
```
 Nah aku gatau nih the proper way buat ngehandle kalau user belum ngecall method ```Long()``` atau ```Short()```

**Comment by mhdiiilham** [comment]
@adibaulia Oh, I see. Saya agak bingung juga sih tadi return nya string kosong.
Btw, tadi saya juga coba buat solve nya pake cara ini

```
//LowerCase returns lowercase of "bulan"
func (b Bulan) LowerCase() Bulan {
	return Bulan(strings.ToLower(b.Long().ToString()))
}

//UpperCase returns UPPERCASE of "bulan"
func (b Bulan) UpperCase() Bulan {
	return Bulan(strings.ToUpper(b.Long().ToString()))
}
```

Mungkin boleh di review lagi bro @adibaulia

**Review by adibaulia — COMMENTED** [review]
i think i will remove the uppercase and lowercase methods because make confused and then golang has ```strings.Tolower()``` and ```strings.ToUpper()```

**Comment by adibaulia** [comment]
minta tolong @mhdiiilham di benerin aja test case nya ntar aku merge. thankyou

**Comment by mhdiiilham** [comment]
> minta tolong @mhdiiilham di benerin aja test case nya ntar aku merge. thankyou

Okay, Saya update test case nya LowerCase & UpperCase di Remove @adibaulia

**Pull request merged**
